import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/Navbar";
import { Lato } from 'next/font/google';


const lato = Lato({
  weight: '400',
  subsets: ['latin'],
})


// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

 

      <body
        className={lato.className}
      >
         <Navbar/>
        {children}
      </body>
    </html>
  );
}
